### ISSUE TITLE
Cannot assign value of type '[ARReferenceImage]' to type 'Set<ARReferenceImage>'

### ISSUE THREAD

**Issue by oxeron** [valvoline/ARKit2-trackingImages#1]
Error with Xcode 10 beta 2 on line 
(configuration as! ARImageTrackingConfiguration).trackingImages = referenceImages

**Comment by valvoline** [comment]
Thanks for reporting. It should be fixed in [b1068a2](https://github.com/valvoline/ARKit2-trackingImages/commit/b1068a2b2a6e0a7080ac66e9be22de0bff3dbfe8)
